repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
        types: [ python ]
      - id: trailing-whitespace
        types: [ python ]
        exclude: ^tests/fixtures/
  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.5.0
    hooks:
      - id: setup-cfg-fmt
        types: [ python ]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: [ --py311-plus ]
        types: [ python ]
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        args: [ --line-length=79 ]
        types: [ python ]
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        types: [ python ]
        args: [ "--ignore=E402,F841,F401,E302,E305", "--exclude=**/settings/**" ]
  - repo: https://github.com/necaris/pre-commit-pyright
    rev: 1.1.53
    hooks:
      - id: pyright
        types: [ python ]